---
deploy_role: "host"
partyid: "{{ host.get('partyid',10000) }}"
eggroll: "{{ host.get('eggroll',{}) }}"
rollsite: "{{ host.get('rollsite',{}) }}"
clustermanager: "{{ host.get('clustermanager',{}) }}"
nodemanager: "{{ host.get('nodemanager',{}) }}"
side: "{{ host.get('side',{}) }}"
db: "{{ host.get('mysql',{}) }}"
fateboard: "{{ host.get('fateboard',{}) }}"
fate_flow: "{{ host.get('fate_flow',{}) }}"
zk: "{{ host.get('zk',{}) }}"
servings: "{{ host.get('servings',{}) }}"
spark: "{{ host.get('spark',{}) }}"
hive: "{{ host.get('hive',{}) }}"
hdfs: "{{ host.get('hdfs',{}) }}"
rabbit: "{{ host.get('rabbitmq',{}) }}"
pulsar: "{{ host.get('pulsar',{}) }}"
nginx: "{{ host.get('nginx',{}) }}"
